services:
  postgres:
    image: postgres:16
    container_name: patika-clone-postgres
    restart: always
    environment:
      POSTGRES_DB: patika_clone_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - patika_clone_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: patika-clone-adminer
    restart: always
    ports:
      - "8081:8080"
volumes:
  patika_clone_data: